version: '3.1'

services:

  backend:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: medicalService-opddata

  db:
    image:  postgres:11
    ports:
      - 5432:32700
    volumes:
      - data:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medicalService-opddata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: